name: Release Java Artifact

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Maven
        run: mvn test -B

  deliver-jar:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build JAR file
        run: mvn package -B
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: target/*.jar

  release:
    needs: deliver-jar
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: release-jar
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.jar"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generateReleaseNotes: true
          token: ${{ secrets.TOKEN }}
